### ISSUE TITLE
Seemingly slow point based operations

### ISSUE THREAD

**Issue by julianblue** [opendatacube/odc-stac#115]
Hi @Kirill888 ,

I am trying to run point based operations on delayed xarray objects that were generated with odc-stac. The process takes substantially longer with odc-stac than with stackstac. Where is my mistake or is this expected ?

Code to generate cubes:
```python
from pystac_client import Client
from odc.stac import load

lon, lat = 9.140625, 50.6807971

catalog = Client.open("https://earth-search.aws.element84.com/v1/")
query = catalog.search(
    collections=["sentinel-2-l2a"],
    datetime="2021-04-06/2021-06-10",
    intersects=dict(type="Point", coordinates=[lon, lat]),
)
itms = query.get_all_items()

stacked = load(itms, resolution=10,crs="EPSG:32632", chunks={})

import stackstac
stacked2 = stackstac.stack(itms, epsg=32632, resolution=10)
```

For odc-stac 
<img width="742" alt="Screenshot 2023-05-09 at 07 28 20" src="https://user-images.githubusercontent.com/21318315/237002340-a2f39816-970c-43ca-b4b8-bc926380fb42.png">

For stackstac
<img width="637" alt="Screenshot 2023-05-09 at 07 28 28" src="https://user-images.githubusercontent.com/21318315/237002393-685a5255-9914-4bba-b725-0a4790ef2954.png">

Thanks in advance.

**Comment by Kirill888** [comment]
stackstac defaults to 1024x1024 spatial chunks, so please test with `chunks={'x': 1024, 'y': 1024}` to have a more fair comparison.

**Comment by Kirill888** [comment]
@julianblue also please add the following

```python
from odc.stac import configure_rio

configure_rio(cloud_defaults=True, aws={"aws_unsigned": True})
```

Somewhere up-top to speed things up some more, this configures GDAL settings that speed up access to COGs on S3 by turning off sidecar file checking.

**Comment by Kirill888** [comment]
With those changes I get very similar result between the two about 4s each (3.7 stackstac, 4.06 for odc-stac, this is reading from Azure hosted notebook, running in us-west-2 on AWS will be different). Also keep in mind that gdal might cache data, so make sure to restart notebook when benchmarking.

**Comment by julianblue** [comment]
@Kirill888 , thanks a lot. This solved it. Should have checked the chunks in advance.
