### ISSUE TITLE
Creating a STAC document that be used to load hyperspectral data from a multi-band tif

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/odc-stac#119]
I'm working with a .tif file that has 65 bands in it and I'm hoping to create a STAC document that can be used to load the data using `odc-stac`.

I've used [rio-stac](https://github.com/developmentseed/rio-stac) to create the [initial document](https://gist.github.com/alexgleith/e01402fff18c235ecb7f1a9c173e21f7), which seems reasonable, but using `odc.stac.load` is throwing an error:

> TypeError: Cannot cast scalar from dtype('float64') to dtype('uint16') according to the rule 'same_kind'

I've tried passing in config, but that didn't change anything. Looking for ideas for hopefully a silly mistake on my part!

``` python
item = rio_stac.create_stac_item(
    in_file,
    input_datetime=file_datetime,
    with_proj=True,
    with_raster=True,
    with_eo=True,
    asset_name="reflectance",
    asset_href=os.path.abspath(filename),
    collection="hsi"
)
item.set_self_href(os.path.abspath(stac_filename))

data = load(
    [item],
    stac_cfg={
        "hsi": {
            "assets": {
                "*": {"data_type": "uint16", "nodata": 0}
            }
        }
    }
)
```

**Comment by alexgleith** [comment]
Setting the `dtype` parameter to `float64` works, actually. Which doesn't make sense, since the bands are reported by GDAL to be `unit16` and the values in the data are clearly between 0-16,000ish.

``` python
data = load(
    [item],
    dtype="float64"
)
```

Result loads, this is `reflectance.1` band

![image](https://github.com/opendatacube/odc-stac/assets/3445853/30a3a18e-a794-4132-ab67-cd4898ca3b4f)

**Comment by Kirill888** [comment]
I'm guessing that would be because `nodata: 0.0` 

https://gist.github.com/alexgleith/e01402fff18c235ecb7f1a9c173e21f7#file-example_hsi-stac-item-json-L137

`odc-stac` should be more robust when parsing `nodata`, just because it is defined a float value doesn't mean it can't be safely cast to uint16. Also weird that it didn't accept override.

Load with type conversion is a supported operation, and judging by the plot `nodata=0` was used during conversion to float + nan.

**Comment by Kirill888** [comment]
@alexgleith can you please provide full stack trace and also `rio info` of the TIFF file. I have no issues casting `0.0` to `uint16` dtype, maybe these things depend on numpy version or platform used? Or it could be just bad `nodata` definition within the file

you can play around with the following settings:

```
src_nodata_override
src_nodata_fallback
fill_value
```

Relevant codes:

https://github.com/opendatacube/odc-stac/blob/52a016be2115f180e7059f67bcc6106fbeba7e8d/odc/stac/_reader.py#L28-L35

https://github.com/opendatacube/odc-stac/blob/52a016be2115f180e7059f67bcc6106fbeba7e8d/odc/stac/_reader.py#L44-L61

https://github.com/opendatacube/odc-stac/blob/52a016be2115f180e7059f67bcc6106fbeba7e8d/odc/stac/_reader.py#L120-L122

**Comment by alexgleith** [comment]
Stack trace:

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 5
      2 eo_bands_subset = item.assets["reflectance"].extra_fields["eo:bands"][0:5]
      4 # Load the data
----> 5 data = load(
      6     [item],
      7     measurements=[i["name"] for i in eo_bands_subset],)
      9 # No need for time
     10 data = data.squeeze("time")

File [/opt/homebrew/lib/python3.11/site-packages/odc/stac/_load.py:610](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/odc/stac/_load.py:610), in load(items, bands, groupby, resampling, dtype, chunks, pool, crs, resolution, anchor, geobox, bbox, lon, lat, x, y, like, geopolygon, progress, fail_on_error, stac_cfg, patch_url, preserve_original_order, **kw)
    607 if progress is not None:
    608     _work = progress(SizedIterable(_work, total_tasks))
--> 610 for _ in _work:
    611     pass
    613 return _with_debug_info(ds, tasks=_tasks)

File [/opt/homebrew/lib/python3.11/site-packages/odc/stac/_utils.py:38](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/odc/stac/_utils.py:38), in pmap(func, inputs, pool)
     34 """
     35 Wrapper for ThreadPoolExecutor.map
     36 """
     37 if pool is None:
---> 38     yield from map(func, inputs)
     39     return
     41 if isinstance(pool, int):

File [/opt/homebrew/lib/python3.11/site-packages/odc/stac/_load.py:601](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/odc/stac/_load.py:601), in load.._do_one(task)
    595 srcs = [
    596     src
    597     for src in (_parsed[idx].get(band, None) for idx, band in task.srcs)
    598     if src is not None
    599 ]
    600 with rio_env(**_rio_env):
--> 601     _ = _fill_2d_slice(srcs, task.dst_gbox, task.cfg, dst_slice)
    602 t, y, x = task.idx_tyx
    603 return (task.band, t, y, x)

File [/opt/homebrew/lib/python3.11/site-packages/odc/stac/_load.py:693](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/odc/stac/_load.py:693), in _fill_2d_slice(srcs, dst_gbox, cfg, dst)
    690 else:
    691     fill_value = nodata
--> 693 np.copyto(dst, fill_value)
    694 if len(srcs) == 0:
    695     return dst

File <__array_function__ internals>:200, in copyto(*args, **kwargs)

TypeError: Cannot cast scalar from dtype('float64') to dtype('uint16') according to the rule 'same_kind'
```

**Comment by alexgleith** [comment]
Passing these in to the `load` function didn't change the error:

```
src_nodata_override=0
src_nodata_fallback=0
fill_value=0
```

**Comment by alexgleith** [comment]
Confirmed that fixing the STAC Document to have `0` as the nodata value makes loading work fine and data is loaded as `dtype=uint16`

**Comment by Kirill888** [comment]
So, this is really two issues here:

1. Load should be more robust to src `nodata` being "an int inside float" 
2. There is no way to override `dtype,nodata,unit` for multi-band assets

By the way `"assets": {"*": {"data_type": "uint16", "nodata": 0}}` configures *fallback* data type and nodata, so this won't be used in this case, since you have that information in the item already.

Maybe we should support 
1. `"assets":{"reflectance": [{}, {}, ...]}` 
2. `"assets":{"reflectance.*": {}}`

as syntax for overriding multi-band asset information.

**Comment by alexgleith** [comment]
Maybe it's a `rio-stac` issue, because `gdalinfo` says:

```
Band 1 Block=2228x1 Type=UInt16, ColorInterp=Gray
  NoData Value=0
Band 2 Block=2228x1 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
```

Which... isn't a float. I can report it over there.

**Comment by alexgleith** [comment]
Closing this, as I have everything working now.

Thanks heaps, @Kirill888. ODC STAC is really impressive at handling this complex dataset in a simple way!
