### ISSUE TITLE
`odc.stac.load` with both `nodata` and `groupby="solar_day"` is not merging scenes properly

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/odc-stac#138]
In short, it appears that passing in a specific (valid) nodata value causes groupby to not work properly.

It's a bit tricky to untangle, but [here's an example notebook](https://gist.github.com/alexgleith/13536a5cabf9440e0d214b541eaf5fca).

Simple reproduction of the issue can be seen in this code:

```python
from pystac_client import Client
from odc.stac import load
from planetary_computer import sign_url

catalog = "https://planetarycomputer.microsoft.com/api/stac/v1"
client = Client.open(catalog)

ll = [177.5, -18.5]
ur = [179.0, -17.0]
bbox = [ll[0], ll[1], ur[0], ur[1]]

items = list(client.search(
    collections=["landsat-c2-l2"],
    datetime="2023-01/2023-03",
    bbox=bbox)
.items())

print(f"Found {len(items)} items")

# Found 40 items

data_grouped = load(
    items,
    resolution=90,
    bbox=bbox,
    measurements=["qa_pixel"],
    chunks={},
    patch_url=sign_url,
    groupby="solar_day",
    nodata=0
)

CLOUD = 3
CLOUD_SHADOW = 4

bitmask = 0
for field in [CLOUD, CLOUD_SHADOW]:
    bitmask |= 1 << field

cloud_grouped = data_grouped.qa_pixel.astype("uint16") & bitmask != 0

count_not_cloud_grouped = (~cloud_grouped).sum(dim="time").compute()
count_not_cloud_grouped.plot.imshow(size=10)
```

![image](https://github.com/opendatacube/odc-stac/assets/3445853/5bde4a20-a41d-4948-81ab-92bf379309fc)

This bright yellow triangle goes away if we remove the `groupby="solar_day"` or if we remove `nodata=0`. I'm pretty sure nodata _is_ `0`, but can't be sure.

**Comment by alexgleith** [comment]
Oh, 🤦.

The issue is that the `qa_pixel` band's `0` bit is the nodata bit, which means `1` is nodata...

My bad!

**Comment by Kirill888** [comment]
@alexgleith looks like we need a custom fuser implemented in `odc.stac.load`, although doing externally in Dask is probably a better option in terms of flexibility, so maybe just some examples would do. Unlike `dc.load` give me "completely unfused" pixels is an option here even when all items share the same timestamp.

**Comment by alexgleith** [comment]
>give me "completely unfused" pixels

Yeah, I see what you're saying. It's nice there's the option for people who know what they're doing!

It's also nice to have an opinionated way of fusing. I wonder if there's a way to make it more obvious that you can fuse by day. (With `groupby="solar_day"`).
