### ISSUE TITLE
Is it possible to retrieve associated metadata?

### ISSUE THREAD

**Issue by fmariv** [opendatacube/odc-stac#166]
Hi,

I’m currently using `odc-stac` and was wondering if it is possible to retrieve metadata associated with the images, such as orbit or instrument mode for Sentinel-1 RTC. I’m specifically looking for a way to access this kind of metadata via the library, but I haven’t found clear information on how to do this in the documentation.

Is this supported by `odc-stac`, or is there a recommended approach for accessing this metadata?

Thanks in advance for your help!

**Comment by maawoo** [comment]
For anyone seeing this issue but not being aware of the Pangeo Discourse, a workaround has been described in this thread:
https://discourse.pangeo.io/t/accessing-metadata-as-variables-in-xarray-datasets-using-odc-stac/4460/4

**Comment by fmariv** [comment]
Thanks for the mention @maawoo. Actually, the proposed workaround worked to me, so I consider this thread closed.
