### ISSUE TITLE
Add a link in the repo to the docs

### ISSUE THREAD

**Issue by rowanwins** [opendatacube/odc-stac#38]
I landed on the [repo homepage](https://github.com/opendatacube/odc-stac) and couldn't see an obvious link to the docs, although I could see a docs directory, so went back to google to search again :)

**Comment by Kirill888** [comment]
Thanks for the feedback, there is a link via `docs passing` badge at the very top of the readme, but it's not an obvious link. Agree that it is worth adding a more explicit link.

**Comment by rowanwins** [comment]
Ah thanks @Kirill888 - yeah that is a little hidden :) 

If there isn't something obvious in the repo README I normally expect to see something in the default github link. 
![link](https://user-images.githubusercontent.com/6735870/153800440-7d16f330-3609-45dd-8084-b37c6f08cd43.png)
