### ISSUE TITLE
AssertionError: Only axis-aligned geoboxes are currently supported

### ISSUE THREAD

**Issue by rsignell-usgs** [opendatacube/odc-stac#40]
I'm relatively new to odc-stac and Digital Earth Africa, and trying out the stac client and odc-stac package to access sentinel-1.    I started with the [digital earth africa sentinel2 example code](https//github.com/opendatacube/odc-stac/blob/develop/notebooks/stac-load-S2-deafrica.py) and that worked fine, but when I tried [adapting it for sentinel-1](https://nbviewer.org/gist/e81f1b7b22979df5dd0303d4bfdb30fa), I'm getting `AssertionError: Only axis-aligned geoboxes are currently supported`, despite trying both projected and lon/lat specification.

I'm guessing this is user error rather than a bug, so suggestions welcome!  :)

**Comment by Kirill888** [comment]
It's clearly a bug in `odc-stac` or possibly `datacube`. Data sources with non-axis aligned geo references aren't that common so don't get tested as much. 

I think this `assert` is over strict, also not very cheap to run, but it was added 3 years ago...

https://github.com/opendatacube/datacube-core/commit/ca61414b9004e1026a0aabf3cb20ec300877b1b8

Only some operations are not supported for non-axis aligned geoboxes, but `odc-stac` is just using it as a container to move geo referencing information around.

**Comment by Kirill888** [comment]
While this has highlighted an important problem, the real issue is with the projection information in STAC data.

https://explorer.digitalearth.africa/stac/collections/s1_rtc/items/46bbaf19-62fd-58c0-9538-9a48c2aec7cc

```
    37.0,      0.0002,      0.0,
    13.0,      0.0,      -0.0002,
    0.0,      0.0,      1.0
```

The order of parameter returned is all messed up, I guess it's using GDAL convention, while stac extension uses row-major, actual files are axis aligned, their transform is:

```
    0.0002,    0,    37,
    0,    -0.0002,    13,
    0,    0,    1
```

so, it's a data provider error.

@alexgleith  :arrow_up: metadata for `s1_rtc` seems to be broken, I don't think it's to stac conversion issue, looks like it's like that in yaml too.

**Comment by Kirill888** [comment]
https://explorer.digitalearth.africa/products/s1_rtc/datasets/46bbaf19-62fd-58c0-9538-9a48c2aec7cc

**Comment by alexgleith** [comment]
Hey @rsignell-usgs thanks for this report.

This is the original metadata, as supplied: https://deafrica-sentinel-1.s3.af-south-1.amazonaws.com/s1_rtc/N12E037/2020/09/02/03F841/s1_rtc_03F841_N12E037_2020_09_02_metadata.json

It has the same order. I'll get Marko from Sinergise to look at the order of the transform parameters.

**Comment by alexgleith** [comment]
Can I confirm that if we do change the axis order in the transform to what GDAL uses, it'll fix it @Kirill888?

**Comment by Kirill888** [comment]
So expected order for proj extension is 
```
sx, 0, tx, 
0, sy, ty,
0,  0,  1
```
flattened: `sx,0,tx,0,sy,ty`

What appears to be in the metadata is: `tx,sx,0,ty,0,sy` which I think is [gdal geotransform order](https://gdal.org/user/raster_data_model.html#affine-geotransform).

which is different from what it is expected in stac
https://github.com/stac-extensions/projection#projtransform

**Comment by Kirill888** [comment]
> Can I confirm that if we do change the axis order in the transform to what GDAL uses, it'll fix it @Kirill888?

@alexgleith not ~_to_~ but **AWAY** from what GDAL uses and into matrix form instead, then serialized in row major order as a flat 9 element array
`sx,0,tx,0,sy,ty,0,0,1`

**Comment by alexgleith** [comment]
`rio info` gives me: `"transform": [0.0002, 0.0, 37.0, 0.0, -0.0002, 13.0, 0.0, 0.0, 1.0]`

Whereas the STAC is `[37, 0.0002, 0, 13, 0, -0.0002]`

I don't know which is correct, though.

Edit: from your [link](https://github.com/stac-extensions/projection#projtransform) the Rasterio Transform is correct.

**Comment by Kirill888** [comment]
https://github.com/stac-extensions/projection/issues/9

**Comment by Kirill888** [comment]
Same issue in stacstack it seems:

https://github.com/gjoseph92/stackstac/issues/132

**Comment by Kirill888** [comment]
@rsignell-usgs you can work-around this issue by disabling proj extension for `s1_rtc` collection with the following config:

```
config = {
    "s1_rtc": {
        "ignore_proj": True
    }
}
```

Then you should be able to load the data, but you will have to supply `crs=` and `resolution=` parameters as these can not be auto-guessed when proj extension is disabled or not available. But you already do that in your example.

**Comment by alexgleith** [comment]
FYI this has been acknowledged by the Sentinel-1 suppliers and they are issuing a fix.

**Comment by alexgleith** [comment]
I believe this has been fixed, for example, here's a newly produced scene: https://explorer.digitalearth.africa/stac/collections/s1_rtc/items/0a461211-1d56-5bb0-8baf-bb9917d8f77f

The transform is:

```
"proj:transform": [
0.0002,
0,
50,
0,
-0.0002,
12,
0,
0,
1
],
```
