### ISSUE TITLE
module 'odc' has no attribute 'stac

### ISSUE THREAD

**Issue by joemcglinchy** [opendatacube/odc-stac#52]
Hi there,

I'm looking forward to using this package, once I can get it installed correctly! I've tried `conda install -c conda-forge odc-stac` and `pip install odc-stac` both to no avail. No errors on the conda install, but with pip install I do receive this error towards the end of the pip install:

```
Installing collected packages: python-dateutil, greenlet, sqlalchemy, psycopg2, lark-parser, datacube, odc-stac
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.7.5
    Uninstalling python-dateutil-2.7.5:
      Successfully uninstalled python-dateutil-2.7.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sat-stac 0.4.1 requires python-dateutil~=2.7.5, but you have python-dateutil 2.8.2 which is incompatible.
```

Here's what I see when importing `odc` into python:
```
>>> import odc
>>> dir(odc)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> odc.stac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'odc' has no attribute 'stac'
```

Has anyone run into this before? I'm running:

Windows 10
Python 3.9.6

haven't tried with a clean environment install, but that is next on my list. 
UPDATE: clean install did the trick... not sure why the install errors previously though. feel free to close if appropriate.

```
conda create -n odc python=3.9
conda activate odc
conda install -c conda-forge odc
python 
>>> import odc.stac
>>>
```

**Comment by Kirill888** [comment]
@joemcglinchy `odc.` is a namespace. `odc-stac` adds `odc.stac` to that namespace, `odc-algo` adds `odc.algo` and so on. So you have to `import odc.stac` not just `import odc` to get access to `odc.stac` module.

Installing with `pip` in a conda environment should be considered as a last resort and done with care as it will pull in other dependencies from `pypi` and not from `conda` and those might clash at DLL level with conda packages causing hard to debug runtime faults. So even though `odc-stac` is a python only package, packages it depends on do include compiled code, so conda install should be preferred.
