### ISSUE TITLE
Support local paths

### ISSUE THREAD

**Issue by gadomski** [opendatacube/odc-stac#56]
`odc-stac` should accept STAC items that have local paths. The underlying error comes from datacube, so _maybe_ the fix should go there? If so we can transfer this issue over.

## Example script

This script uses a MODIS file from the Planetary Computer (staging), but any tif will do. Requires [stactools](https://github.com/stac-utils/stactools).

```python
import datetime
import odc.stac
import stactools.core.create

bbox = [-107, 39, -106, 40]
file_name = "MYD10A1.A2020335.h10v04.061.2020357064115_NDSI_Snow_Cover.tif"
item = stactools.core.create.item(file_name)  # asset href is set to "MYD10A1.A2020335.h10v04.061.2020357064115_NDSI_Snow_Cover.tif"
item.common_metadata.start_datetime = datetime.datetime(2020, 11, 30)
item.common_metadata.end_datetime = datetime.datetime(2020, 11, 30, 23, 59, 59)
xarray = odc.stac.load([item], bands="data", resolution=500, bbox=bbox)
```

## Expected behavior

It works

## Actual behavior

```
Traceback (most recent call last):
  File "/Users/gadomski/Code/odc-stac/scripts/local_path.py", line 10, in <module>
    xarray = odc.stac.load([item], bands="data", resolution=500, bbox=bbox)
  File "/Users/gadomski/Code/odc-stac/odc/stac/_load.py", line 462, in load
    return dc_load(
  File "/Users/gadomski/Code/odc-stac/odc/stac/_dcload.py", line 191, in dc_load
    return Datacube.load_data(
  File "/Users/gadomski/.virtualenvs/odc-stac/lib/python3.9/site-packages/datacube/api/core.py", line 768, in load_data
    return Datacube._xr_load(sources, geobox, measurements,
  File "/Users/gadomski/.virtualenvs/odc-stac/lib/python3.9/site-packages/datacube/api/core.py", line 701, in _xr_load
    _fuse_measurement(data_slice, datasets, geobox, m,
  File "/Users/gadomski/.virtualenvs/odc-stac/lib/python3.9/site-packages/datacube/api/core.py", line 902, in _fuse_measurement
    src = new_datasource(BandInfo(ds, measurement.name, extra_dim_index=extra_dim_index))
  File "/Users/gadomski/.virtualenvs/odc-stac/lib/python3.9/site-packages/datacube/drivers/readers.py", line 110, in new_datasource
    return source_type(band)
  File "/Users/gadomski/.virtualenvs/odc-stac/lib/python3.9/site-packages/datacube/storage/_rio.py", line 223, in __init__
    filename = _url2rasterio(band.uri, band.format, band.layer)
  File "/Users/gadomski/.virtualenvs/odc-stac/lib/python3.9/site-packages/datacube/storage/_rio.py", line 297, in _url2rasterio
    raise ValueError("Expect either URL or /vsi path")
ValueError: Expect either URL or /vsi path
```

**Comment by Kirill888** [comment]
@gadomski I think it's because we assume that asset href is absolute without forcing it to be absolute:

https://github.com/opendatacube/odc-stac/blob/e33f033c6bbb76a1dc3c085837211a518255d2df/odc/stac/_eo3.py#L608

and without recording self link (datacube supports relative links, but it needs to know relative to what obviously):

https://github.com/opendatacube/odc-stac/blob/e33f033c6bbb76a1dc3c085837211a518255d2df/odc/stac/_eo3.py#L652

How does self link look like in that case? Will simply populating `location` with stringified self link work in this case?

**Comment by gadomski** [comment]
PySTAC has a `make_absolute_href` utility that can resolve a relative link w.r.t. its location (e.g. using the `self` link on the `Item`): https://github.com/stac-utils/pystac/blob/a6c8927dfb1f1f92f60937b3022c499137416468/pystac/utils.py#L249-L284. Since we have PySTAC as a dependency already, could use that?

If so, I would recommend upgrading the PySTAC dependency to `>= 1.4.0` (latest version) -- there was a bug in the `make_absolute_href` function that was fixed in 1.3.0: https://github.com/stac-utils/pystac/pull/697.

**Comment by Kirill888** [comment]
Well, self link is not set using sample code above. So that just raises an error, I think keeping links relative but extracting self link and recording that when doing stac -> odc is preferred way.

In the `next` branch I'm using `asset.get_absolute_href()` 
https://github.com/opendatacube/odc-stac/blob/7a91cd4892f8cc1449fed1a0703428b351fc5d2e/odc/stac/_mdtools.py#L553-L557

**Comment by gadomski** [comment]
`self` link is not required, so relying on it seems fragile? The pystac function doesn't error if there's no self link, it just resolves using pathlib.abspath: https://github.com/stac-utils/pystac/blob/a6c8927dfb1f1f92f60937b3022c499137416468/pystac/utils.py#L238.

**Comment by Kirill888** [comment]
> self link is not required, so relying on it seems fragile?

We are not "relying" on it, if it's not set and all assets are specified with absolute href things would work as expected.

Question is this: "if assets are specified with relative href and item does not specify `self` link what behaviour is expected?"

- Raise an error as location of assets is not well-defined.
- Assume that current working directory is a good substitute for `self` link

Honestly, I think that raising an error in this case is preferable, as long as it's clear about the problem description. Something like

```
ERROR: Asset locations can not  be determined.
   STAC Item '{item_id}' uses relative links for asset '{asset-name}', but does not define "self" link.

   If assets are on your local computer do the following:
   "some suggested work-around user can do on STAC items before calling stac.load again"
```

**Comment by Kirill888** [comment]
related: https://github.com/stac-utils/pystac/issues/754

so it seems that `pystac` assumes that current working directory is a reasonable substitute for missing self link, personally I feel like it's not a good choice.

**Comment by gadomski** [comment]
> so it seems that pystac assumes that current working directory is a reasonable substitute for missing self link, personally I feel like it's not a good choice.

What's the alternative? Obviously, if you have a `parent` or `root` you can try to resolve off of that, but if you only have relative paths, I'm not sure there's a better answer then "assume current working directory."

**Comment by Kirill888** [comment]
The alternative is to treat it as an error. If my code reads an item from `/tmp/` while running in `$HOME` is it more appropriate to resolve relative to `/tmp/` or relative to `$HOME`? Well, `pystac` thinks that `$HOME` is the right choice even when you used `Item.from_file("/tmp/some.geojson")`.

**Comment by Kirill888** [comment]
another alternative is to provide "fallback self link", or some other mechanism to keep track of "actual location from which stac document was read even if it is not recorded in self link".

**Comment by gadomski** [comment]
> another alternative is to provide "fallback self link", or some other mechanism to keep track of "actual location from which stac document was read even if it is not recorded in self link".

Yeah, this is the mechanism that PySTAC uses -- when you read a STAC object from a location, the object's self href is set.

But in the absence of "read-from" information, I agree that the two alternatives are to either error, or use current working directory. My preference is to use current working directory. If we go the error path, we should make sure to document how to work around the issue (e.g. `item.assets["key"].href = os.path.abspath(item.assets["key"].href)`)

**Comment by Kirill888** [comment]
ok, so if you were to write this out into directory next to tif file and then read it back in with `Item.from_file(...)` you'd have self link populated? I didn't know that `.from_file(..).to_dict()` injects extra links if not present, I guess it makes sense.

**Comment by gadomski** [comment]
> didn't know that .from_file(..).to_dict() injects extra links if not present, I guess it makes sense.

Yeah, happens here: https://github.com/stac-utils/pystac/blob/e5d010f94cf718a94995ea5883325faa820f50c4/pystac/stac_object.py#L515.

**Comment by Kirill888** [comment]
- if self link is not set in the data
- and pystac didn't inject it during construction either via `.from_file` or with `.from_dict({..}, href="..")` 
- then "assume current directory"? Not too sure about that

your code above could have been like this instead:

```python
file_name = "/data/myd10a1/items/2020/MYD10A1.A2020335.h10v04.061.2020357064115_NDSI_Snow_Cover.tif"
```

~in which case error won't been seen until after dask graph evaluation and then it would some criptic gdal error~
edit: actually then it would probably work as absolute url

**Comment by gadomski** [comment]
but `/data/...` is an absolute path so there's no assumptions to make, right?

**Comment by Kirill888** [comment]
@gadomski is it something that needs fixing before switching over to `odc-geo` implementation? `next` branch resolves to absolute url with current working directory as default (because that's what pystac does)?

**Comment by gadomski** [comment]
Nope, not urgent, was just something I bumped up against when debugging another issue.

**Comment by Kirill888** [comment]
real issue is really: "relative links are not properly handled as `self` link is ignored even when set"

**Comment by gadomski** [comment]
> relative links are not properly handled as self link is ignored even when set

Is that true? If so that would be surprising to me -- IIRC relative links are resolved relative to their owner's self href if possible.

**Comment by Kirill888** [comment]
This is the code that extracts href from asset in currently released version:

https://github.com/opendatacube/odc-stac/blob/32f57a27391e52a1d3452c0c820dfe69e44d8a37/odc/stac/_eo3.py#L608

I assume this remains relative if that's how it is recorded regardless of the status of item's self link?

**Comment by Kirill888** [comment]
if this was just about pixel loading I would simply replace it with `.get_absolute_href()`, but since this is also about conversion to datacube metadata and it supports relative/absolute paths for bands it's more appropriate to propagate self link.

**Comment by gadomski** [comment]
> if this was just about pixel loading I would simply replace it with .get_absolute_href(), but since this is also about conversion to datacube metadata and it supports relative/absolute paths for bands it's more appropriate to propagate self link.

I guess part of the issue is that PySTAC does a lot of implicit href manipulation under the hood, so it can be hard to tell where a given href was actually generated from.

When I'm working w/ PySTAC to e.g. build out catalogs, I often work like this:
1. Set the href of root catalog/collection of my tree
2. Use [normalize_hrefs](https://pystac.readthedocs.io/en/stable/api/pystac.html?highlight=normalize#pystac.Catalog.normalize_hrefs) to put the rest of my tree into a known href state
3. Use [make_all_asset_hrefs_relative](https://pystac.readthedocs.io/en/stable/api/pystac.html?highlight=normalize#pystac.Catalog.make_all_asset_hrefs_relative) (or its sibling, `*_absolute`) to put all of my asset hrefs into a known state

I wonder if a similar approach may be appropriate for datacube metadata conversion -- I realize you don't always have a catalog to work with, but some sort of href normalization on the way in might make sense, whether that's using PySTAC's methods or your own.

**Comment by Kirill888** [comment]
- Are these available on `Item.` class?
- Should `stac.load` call those or equivalent or should it assume that this was done already, and only if needed. Given that it's inputs mostly come from stac-api is this extra computation worth it?

**Comment by gadomski** [comment]
> Are these available on Item. class?

The asset ones are, yes: https://pystac.readthedocs.io/en/stable/api/pystac.html?highlight=make_asset#pystac.Item.make_asset_hrefs_absolute.

> Should stac.load call those or equivalent or should it assume that this was done already, and only if needed. Given that it's inputs mostly come from stac-api is this extra computation worth it?

IMO `stac.load` should be able to accept _any_ STAC object, regardless of its source. While we now use the library mostly in an API context, this may not always be the case, e.g. in the instance of large static catalogs on a user's machine, or on-the-fly STAC objects generated by a user as a quick way to get geospatial assets into xarrays.

**Comment by Kirill888** [comment]
`odc-stac` no longer uses datacube, this issue is no longer relevant.
