### ISSUE TITLE
pystac-client==0.3.3 (current release) breaks example notebooks

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/odc-stac#59]
Seems this is an issue with STAC and Element84 implementation which is falling foul of a change in pystac-client which enforces the use of GEOJSON search endpoints:
https://github.com/stac-utils/pystac-client/issues/159

Has the rather sad side effect of breaking the odc-stac example.
Workaround for the moment is to pin pystac-client==0.3.2 
Hopefully element84 will make necessary changes.

**Comment by gadomski** [comment]
[pystac-client is now at v0.4.0](https://github.com/stac-utils/pystac-client/releases/tag/v0.4.0) and there is no pin in this repository (as far as I can see), so IMO this issue can be closed as not planned, @Kirill888.
