### ISSUE TITLE
[URGENT] stac_load: ValueError: No such band or alias: 'red'

### ISSUE THREAD

**Issue by xxie12** [opendatacube/odc-stac#73]
I followed exactly this tutorial for LandSat 9 Collection 2 data,
(https://gist.github.com/rsignell-usgs/8cc1d3b8832cd89f984f75db761eaf59)
and keeps getting error when running 
```
search = cat.search(
    collections = [collection_id],
    bbox = bbox,
    datetime = time,
    limit = 100,
)

items_dict = search.get_all_items_as_dict()['features']

item_collection = pystac.ItemCollection(items_dict)

proj = ProjectionExtension.ext(item_collection[0])

output_crs = CRS.from_epsg(proj.epsg)
resolution = resyx_(proj.transform[4], proj.transform[0])

dc = stac_load(item_collection,
               bands=("red", "green", "blue"),
               chunks={"x": 2048, "y": 2048},
               output_crs=output_crs,
               resolution=resolution,
               groupby='solar_day',
               stac_cfg=cfg
)
```
![xxs](https://user-images.githubusercontent.com/82345895/175392408-8a75e872-904a-4887-a5df-6e5067dcb791.PNG)

it keeps getting me the error message and I followed exactly the steps this tutorial has and chose the same collection id. Could you please help me with this? Thanks!

**Comment by Kirill888** [comment]
@xxie12 what's the urgency exactly?

1. you no longer need to configure output_crs/resolution, newer versions of odc.stac should auto-detect native projection and resolution
2. Please share exact query you are performing, or even better the result of a query you are getting
3. Also state what version of odc-stac you are using

instead of using red/green/blue try using canonical names for those bands and see if that works.

**Comment by xxie12** [comment]
```
search = cat.search(
    collections = "landsat-c2l1",
    bbox = [-123.17, 37.64, -123.18,  37.65],
    datetime = 2022-01-01/2022-01-31,
    limit = 100,
)
```
When I tried deleting the configuration for out_crs and resolution, it showed this:

```
  File "/mnt/d/BrandonLucia/api/myproject/myapplication/lib/python3.8/site-packages/odc/stac/_load.py", line 477, in load
    raise ValueError("Failed to auto-guess CRS/resolution.")
ValueError: Failed to auto-guess CRS/resolution.
```
Collection I am working on is landsat-c2l1
odc-stac version is 0.3.0
Is there any temporary method I can solve this band's name problem? Thanks.
