### ISSUE TITLE
DataArray contains nan-buffer?

### ISSUE THREAD

**Issue by maawoo** [opendatacube/odc-stac#83]
Hi all,
I've mostly used [stackstac](https://github.com/gjoseph92/stackstac) by now and wanted to see if our dataset's STAC metadata is also usable with this library. The overview on technical differences between both libraries provided in #54 is very helpful. In practice, however, I've also noticed that the DataArray created by odc-stac adds a nan-buffer resulting in a slightly larger spatial extent. I was wondering if this is intended? Or is something going wrong on my side? I was not able to find anything about this in other issues or in the documentation.
Here is how I'm loading the dataset in both libraries, screenshots of the DataArrays and visualizations of a subset to highlight the problem:

```python
# stackstac
ds_st = stackstac.stack(items=nrb_catalog, assets=['vh'], dtype=np.dtype('float32'), chunksize=(-1, 1, 2048, 2048))

# odc-stac
nrb_items = nrb_catalog.get_all_items()
ds_odc = odc.stac.load(items=nrb_items, bands=['vh'], chunks={'x': 2048, 'y': 2048})
ds_odc = ds_odc.chunk(chunks={'time':-1})
```
stackstac
![Screenshot 2022-08-08 at 16 11 14](https://user-images.githubusercontent.com/56583917/183439319-9955fa67-5f39-49eb-bf5d-aabe66748cec.png)

odc-stac
![Screenshot 2022-08-08 at 16 10 29](https://user-images.githubusercontent.com/56583917/183439346-6c15ac93-a9e6-4505-853b-6a1318fd0874.png)

----------

stackstac
![Screenshot 2022-08-08 at 16 21 27](https://user-images.githubusercontent.com/56583917/183441133-46dcdd4c-6154-4950-8c30-083e53439761.png)

odc-stac
![Screenshot 2022-08-08 at 16 21 48](https://user-images.githubusercontent.com/56583917/183441170-f74ef284-e3f9-4521-bf5f-a69605025163.png)

**Comment by gadomski** [comment]
I've seen this sort of nodata buffer appear when the Item `geometry` is larger/different than the asset's bounds -- `odc-stac` uses the item geometry to define the spatial extents of the output xarray. Check your item geometry and see if it is different than your asset geometry. Since STAC Items are GeoJSON features, I usually just load both the Item and the asset into QGIS and visually compare the two.

**Comment by maawoo** [comment]
Spot-on, thanks @gadomski!

![Screenshot 2022-08-08 at 17 39 28](https://user-images.githubusercontent.com/56583917/183457403-46078cfc-ce8c-4725-8c96-9db2a74243df.png)
