### ISSUE TITLE
stac_load returns artefacts and NaN 

### ISSUE THREAD

**Issue by scotjohn** [opendatacube/odc-stac#84]
Hello,

I am using odc-stac 0.3.1 and working with data from the Planetary Computer, similar like this:
```
    catalog = pystac_client.Client.open( "https://planetarycomputer.microsoft.com/api/stac/v1")

    query = catalog.search(
        intersects=aoi,
        collections=["sentinel-2-l2a"], 
        datetime = "2017-06-02/2017-06-02"
    )
    items = list(query.get_items())
    items = [planetary_computer.sign(item) for item in items]

    ds = stac_load(
        items=items,
        bands=["B04"],
        resolution=60,
        crs='EPSG:32632',
        groupby="solar_day",
    )
```

I noticed strange behaviour from stac_load which produces artefacts as follows:
![grafik](https://user-images.githubusercontent.com/34665025/183472682-775cc7ec-5fb8-44f2-a548-ada7e9c83be2.png)

The stac items in this case have different source CRS which however should be handled by stac_load. Also I tried to input only items that share the same CRS, which did not prevent from producing aboves artefacts. The underlying original image data as downloaded from the Planetary Computer (e.g. by downloading item.assets["B04"].href) look OK.

A further problem (not sure if interrelated) arises when producing outputs with 100 m resolution (i.e. stac_load(..., resolution=100) which have unexpeced nodata, see white pixels (NaN): 
![grafik](https://user-images.githubusercontent.com/34665025/183470452-9762ca3e-0f9a-4403-8b65-1b24670d030e.png)
...while original 10m resolution data looks as follows:
![grafik](https://user-images.githubusercontent.com/34665025/183470852-7ebca4a1-157b-47ed-b74f-0fe06e96ca61.png)

I am grateful for any hint or idea what is causing this behaviour.

**Comment by Kirill888** [comment]
It's a known issue with `rasterio==1.3.0`, has been fixed in rasterio but not in any released version yet

https://github.com/rasterio/rasterio/pull/2512

**Comment by scotjohn** [comment]
Thank you for your answer. I downgraded rasterio to <1.3.0 and things are working now again.
