### ISSUE TITLE
Asset dtype from STAC raster extension not being used

### ISSUE THREAD

**Issue by scottyhq** [opendatacube/odc-stac#9]
neat project! I'm trying this out with an example static STAC catalog and noticed that all data variables are cast to uint16, despite [STAC items](https://github.com/scottyhq/sentinel1-rtc-stac/blob/97694e54911ef2b363a30ab216e916102deaa280/12SYJ/2016/S1B_20161121_12SYJ_ASC/S1B_20161121_12SYJ_ASC.json#L127-L136) with the raster extension specifying float32 dtypes:

```python
import odc.stac
import pystac

cat = pystac.read_file('https://raw.githubusercontent.com/scottyhq/sentinel1-rtc-stac/main/12SYJ/catalog.json')
items = list(cat.get_all_items())
ds = odc.stac.load(items,
                   #bands=["gamma0_vv", "gamma0_vh", "incidence"],
                   chunks={},
                  )
ds
```
<img width="728" alt="image" src="https://user-images.githubusercontent.com/3924836/138932342-6a3da635-1396-4ac5-b641-9e1dad86bc3b.png">

**Comment by Kirill888** [comment]
@scottyhq my guess it's because `eo:bands` extension is not listed in stac_extensions section of the item

https://github.com/scottyhq/sentinel1-rtc-stac/blob/97694e54911ef2b363a30ab216e916102deaa280/12SYJ/2016/S1B_20161121_12SYJ_ASC/S1B_20161121_12SYJ_ASC.json#L185-L189

you can supply dtype via config though

**Comment by scottyhq** [comment]
> @scottyhq my guess it's because eo:bands extension is not listed in stac_extensions section of the item

Thanks for looking at this @Kirill888 ! I think you mean `raster` rather than `eo:bands`? The raster extension is listed at the collection level https://github.com/scottyhq/sentinel1-rtc-stac/blob/97694e54911ef2b363a30ab216e916102deaa280/collection.json#L57 

The catalog was created with pystac, which I thought automatically adds extensions to the metadata where necessary when created (apparently not for the `raster` extension though... https://github.com/stactools-packages/sentinel1/blob/64b2ce86309ce7ecbeca103573c3a607f414dd37/src/stactools/sentinel1/rtc/stac.py#L145-L147).  (EDIT: cc @matthewhanson), is this a bug in pystac, or should tools like odc-stac generally also read collection metadata if an item links to it?

**Comment by Kirill888** [comment]
@scottyhq yes you are right, I meant `raster`. I think extensions need to be specified on each stac item independent of Collection they belong to.

I think what's happening in the code you have linked is this:

1. Enabled extensions are defined on an Item, not on an Asset, Asset only contains the data
2. Code adds raster data to an Asset that has not been attached to an Item yet, so RasterExtension can not add itself to an Item
3. By the time asset is attached to an Item it has raster extension data, but it does not keep enough state to tell the Item that it has raster extension data

I think if that code added Asset to an Item first, then you would get correct extension list on an Item

**Comment by Kirill888** [comment]
I think Scott meant to cc @matthewhanson regarding pystac
